RazorPagesWithVenkat/Pages/Employees/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesWithVenkat.Models;
using RazorPagesWithVenkat.Services;

namespace RazorPagesWithVenkat.Pages.Employees
{

    public class DeleteModel : PageModel
    {
        public readonly IEmployeeRepository employeeRepository; 
        public DeleteModel(IEmployeeRepository employeeRepository)
        {
            this.employeeRepository = employeeRepository; 
        }

        [BindProperty]
        public Employee Employee { get; set; }
        public IActionResult OnGet(int id)
        {
            Employee = employeeRepository.GetEmployee(id); 
            
            if (Employee == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page(); 
        }

        public IActionResult OnPost()
        {
            Employee deletedEmployee = employeeRepository.Delete(Employee.Id); 

            if (deletedEmployee == null)
            {
                return RedirectToPage("/NotFound");
            }

            return RedirectToPage("Index");
        }
    }
}

RazorPagesWithVenkat/Pages/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesWithVenkat.Models;
using RazorPagesWithVenkat.Services;

namespace RazorPagesWithVenkat.Pages.Employees
{
    public class DetailsModel : PageModel
    {
        private readonly IEmployeeRepository employeeRepository;

        public DetailsModel(IEmployeeRepository employeeRepository)
        {
            this.employeeRepository = employeeRepository;
        }

        [TempData]
        public string Message { get; set; }

        public Employee Employee { get; private set; }

        public IActionResult OnGet(int id)
        {
            Employee = employeeRepository.GetEmployee(id); 

            if (Employee == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }

    }
}

RazorPagesWithVenkat/Pages/Employees/Edit.cshtml.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesWithVenkat.Models;
using RazorPagesWithVenkat.Services;

namespace RazorPagesWithVenkat.Pages.Employees
{
    public class EditModel : PageModel
    {
        private readonly IEmployeeRepository employeeRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EditModel(IEmployeeRepository employeeRepository, IWebHostEnvironment webHostEnvironment)
        {
            this.employeeRepository = employeeRepository;
            // IWebHostEnvironment service allows us to get the
            // absolute path of WWWRoot folder
            this.webHostEnvironment = webHostEnvironment;
        }
        [BindProperty]
        public Employee Employee { get; set; }

        // We use this property to store and process
        // the newly uploaded photo
        [BindProperty]
        public IFormFile Photo { get; set; }

        [BindProperty]
        public bool Notify { get; set; }

        public string Message { get; set; }
        // Make the id parameter optional
        public IActionResult OnGet(int? id)
        {
            // if id parameter has value, retrieve the existing
            // employee details, else create a new Employee
            if (id.HasValue)
            {
                Employee = employeeRepository.GetEmployee(id.Value);
            }
            else
            {
                Employee = new Employee();
            }

            if (Employee == null)
            {
                return RedirectToPage("/NotFound"); 
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {
                    // If a new photo is uploaded, the existing photo must be
                    // deleted. So check if there is an existing photo and delete
                    if (Employee.PhotoPath != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath,
                            "images", Employee.PhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    // Save the new photo in wwwroot/images folder and update
                    // PhotoPath property of the employee object
                    Employee.PhotoPath = ProcessUploadedFile();
                }

                // If Employee ID > 0, call Update() to update existing 
                // employee details else call Add() to add new employee
                if (Employee.Id > 0)
                {
                    // Running invalid ModelState before [BindProperty] was put on Employee, the below
                    // line would not be executed, so the page would throw a null reference error
                    Employee = employeeRepository.Update(Employee);
                }
                else
                {
                    Employee = employeeRepository.Add(Employee);
                }
                return RedirectToPage("Index");
            }
            return Page();
        }

        public IActionResult OnPostUpdateNotificationPreferences(int id)
        {
            if (Notify)
            {
                Message = "Thank you for turning on notifications";
            }
            else
            {
                Message = "You have turned off email notifications";
            }

            //this gets passed to the RedirectToPage method
            TempData["message"] = Message;

            return RedirectToPage("Details", new { id = id }); 
        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

RazorPagesWithVenkat/Pages/Employees/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesWithVenkat.Models;
using RazorPagesWithVenkat.Services;

namespace RazorPagesWithVenkat.Pages.Employees
{
    public class IndexModel : PageModel
    {
        private readonly IEmployeeRepository employeeRepository;

        public IEnumerable<Employee> Employees { get; set; }

        public IndexModel(IEmployeeRepository employeeRepository)
        {
            this.employeeRepository = employeeRepository; 
        }
        public void OnGet()
        {
            Employees = employeeRepository.GetAllEmployees();
        }
    }
}

RazorPagesWithVenkat/Pages/Employees/Delete.cshtml
@page "{id}"
@model RazorPagesWithVenkat.Pages.Employees.DeleteModel
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Confirmation</h1>

<div class="alert alert-danger">
    <h5>Are you sure you want to delete employee- @Model.Employee.Name</h5>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a asp-page="/Employees/Index" class="btn btn-primary">No</a>
    </form>
</div>

RazorPagesWithVenkat/Pages/Employees/Details.cshtml
@* route parameters below. without it we get a 404 *@
@page "/employees/view/{id:min(1)}"
@model RazorPagesWithVenkat.Pages.Employees.DetailsModel
@{
    ViewData["Title"] = "Details"; 
    var photoPath = "~/images/" + (Model.Employee.PhotoPath ?? "noimage.jpg");
}

<div class="row justify-content-center m-3">
    @if (Model.Message != null)
            {
                <div class="col-sm-8">
                    <div class="alert alert-primary">
                        @Model.Message
                    </div>
                </div>
            }
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h1>@Model.Employee.Name</h1>
            </div>

            <div class="card-body text-center">
                <img class="card-img-top" src="@photoPath" asp-append-version="true" />

                <h4>Employee ID : @Model.Employee.Id</h4>
                <h4>Email : @Model.Employee.Email</h4>
                <h4>Department : @Model.Employee.Department</h4>

            </div>
            <div class="card-footer text-center">
                <a asp-page="index"
                   class="btn btn-primary">Back</a>
                <a href="#" class="btn btn-primary">Edit</a>
                <a href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

RazorPagesWithVenkat/Pages/Employees/Edit.cshtml
@*When adding a new employee we would not pass any ID value.
    So, make the id route parameter optional.*@
@page "{id:min(1)?}/{handler?}"
@model RazorPagesWithVenkat.Pages.Employees.EditModel
    @{
        var photoPath = "~/images/" + (Model.Employee.PhotoPath ?? "noimage.jpg");
        // If Employee ID > 0, then we are editing an existing employee else creating new
        // employee. So set the pageHeader variable text accordingly
        var pageHeader = Model.Employee.Id > 0 ? "Edit" : "Create";
        ViewData["Title"] = pageHeader;
    }
    <h1>Notification preferences</h1>

    <form method="post" asp-page-handler="UpdateNotificationPreferences">
        <input asp-for="Notify" class="form-check-input" />
        <label asp-for="Notify" class="form-check-label">
            Receive email notifications when my details change
        </label>
        <button type="submit" class="btn btn-primary">
            Update Notification Preferences
        </button>
    </form>

    <hr />

    <h1>@pageHeader</h1>

    <form method="post" class="mt-3" enctype="multipart/form-data" asp-page-handler="OnPost">
        @*Use hidden input elements to store employee id which
        we need when we submit the form*@
        <input hidden asp-for="Employee.Id" />
        <input hidden asp-for="Employee.PhotoPath" />

        <div asp-validation-summary="All" class="text-danger"></div>

        @*asp-for tag helper takes care of displaying the existing
        data in the respective input elements*@
        <div class="form-group row">
            <label asp-for="Employee.Name" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Employee.Name" class="form-control" placeholder="Name">
                <span asp-validation-for="Employee.Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Employee.Email" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Employee.Email" class="form-control" placeholder="Email">
                <span asp-validation-for="Employee.Email" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Employee.Department" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="Employee.Department" class="custom-select mr-sm-2"
                        asp-items="Html.GetEnumSelectList<Dept>()">
                    <option value="">Please Select</option>
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Employee.Department" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="Employee.Department" class="custom-select mr-sm-2"
                        asp-items="Html.GetEnumSelectList<Dept>()">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="Employee.Department" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <div class="custom-file">
                    @*Photo property type is IFormFile, so ASP.NET Core
                    automatically creates a FileUpload control  *@
                    <input asp-for="Photo" class="custom-file-input form-control">
                    <label class="custom-file-label">Click here to change photo</label>
                </div>
            </div>
        </div>

        <div class="form-group row col-sm-4 offset-4">
            <img class="imageThumbnail" src="@photoPath" asp-append-version="true" />
        </div>

        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Update</button>
                <a asp-page="/Employees/Index" class="btn btn-primary">Cancel</a>
            </div>
        </div>

        @*This jquery code is required to display the selected
        file name in the file upload controls*@

        @section Scripts {
            <script>
                $(document).ready(function () {
                    $('.custom-file-input').on("change", function () {
                        var fileName = $(this).val().split("\\").pop();
                        $(this).next('.custom-file-label').html(fileName);
                    });
                });
            </script>

            <partial name="_ValidationScriptsPartial" />
        }
    </form>

RazorPagesWithVenkat/Pages/Employees/Index.cshtml
@page 
@model RazorPagesWithVenkat.Pages.Employees.IndexModel
@{
    ViewData["Title"] = "Index"; 
}

<h1>Employees</h1>

<div class="card-deck">
    @foreach(var employee in Model.Employees)
    {
        var photoPath = "~/images/" + (employee.PhotoPath ?? "noimage.jpg");

        <div class="card m-3" style="min-width: 18rem; max-width:30.5%;">
            <div class="card-header">
                <h3>@employee.Name</h3>
            </div>

            <img class="card-img-top imageThumbnail" src="@photoPath"
                 asp-append-version="true" />

            <div class="card-footer text-center">
                <a asp-page="/Employees/Details" ASP-ROUTE-ID="@employee.Id" class="btn btn-primary m-1">View</a>
                <a asp-page="/Employees/Edit" asp-route-ID="@employee.Id"class="btn btn-primary m-1">Edit</a>
                <a asp-page="/Employees/Delete" asp-route-ID="@employee.Id" class="btn btn-danger m-1">Delete</a>
            </div>
        </div>
    }
</div>